#index:
#    path: /
#    controller: App\Controller\DefaultController::index

questions_reader:
  path: /questions
  methods: GET
  controller: App\Controller\Questions\QuestionsReader

questions_writer:
  path: /questions
  methods: POST
  controller: App\Controller\Questions\QuestionsWriter

